# Generated by Django 4.1.2 on 2023-10-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drname', models.CharField(max_length=250)),
                ('daytime', models.TimeField()),
                ('date', models.DateField()),
                ('speciality', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
